version: "3"
virtualmachines:
- name: host
  image: projects/tmm-instruqt-11-26-2021/global/images/virt-rhel-9-2-08-01-23
  shell: /bin/bash
  environment:
    TERM: xterm
  machine_type: n2-standard-4
  nested_virtualization: true
  allow_external_ingress:
  - http
  - https
  - high-ports
secrets:
- name: SSHKEY
- name: ACTIVATION_KEY
