version: "3"
virtualmachines:
- name: host
  #image: projects/tmm-instruqt-11-26-2021/global/images/virt-rhel-9-2-07-28-23-2
  image: projects/tmm-instruqt-11-26-2021/global/images/virt-rhel-9-2-08-03-23-3
  shell: /bin/bash
  environment:
    TERM: xterm
  machine_type: n2-standard-4
  nested_virtualization: true
secrets:
- name: ACTIVATION_KEY
- name: SSHKEY
