version: "3"
virtualmachines:
- name: rhel1
  image: projects/tmm-instruqt-11-26-2021/global/images/satellite-client-test1-7-19-23
  shell: /bin/bash
  environment:
    TERM: xterm
  machine_type: n1-standard-1
  allow_external_ingress:
  - http
  - https
  - high-ports
- name: rhel2
  image: projects/tmm-instruqt-11-26-2021/global/images/satellite-client-test1-7-19-23
  shell: /bin/bash
  environment:
    TERM: xterm
  machine_type: n1-standard-1
  allow_external_ingress:
  - http
  - https
  - high-ports
- name: satellite
  image: projects/tmm-instruqt-11-26-2021/global/images/satellite-test-7-19-23
  shell: /bin/bash
  environment:
    TERM: xterm
  machine_type: n1-standard-8
  allow_external_ingress:
  - http
  - https
  - high-ports
secrets:
- name: ACTIVATION_KEY
